ishuhui/models/chapter.py
from ishuhui.extensions.flasksqlalchemy import db
import ishuhui.data


class Chapter(db.Model):
    __tablename__ = 'chapters'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    title = db.Column(db.String(256), nullable=False)
    comic_id = db.Column(db.Integer, nullable=False)
    chapter_number = db.Column(db.Integer, nullable=False)
    front_cover = db.Column(db.String(256), nullable=True)
    refresh_time = db.Column(db.DateTime, nullable=True)
    images = db.Column(db.Text, nullable=True)

    def comic(self):
        return ishuhui.data.get_comic(self.comic_id)

ishuhui/models/comic.py
import ishuhui.data
from ishuhui.extensions.flasksqlalchemy import db


class Comic(db.Model):
    __tablename__ = 'comics'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    title = db.Column(db.String(256), nullable=False)
    description = db.Column(db.String(1024), nullable=False)
    refresh_time = db.Column(db.DateTime, nullable=True)
    author = db.Column(db.String(256), nullable=True)
    classify_id = db.Column(db.Integer, nullable=False)
    front_cover = db.Column(db.String(256), nullable=True)

    @property
    def chapters_count(self):
        return ishuhui.data.count_chapters(self.id)

ishuhui/controllers/admin.py
from flask import Blueprint, render_template, current_app, session
from flask import abort, jsonify
from flask_login import current_user

import ishuhui.tasks.task as task
from ..models.chapter import Chapter
from ..models.comic import Comic
from ..tasks.celery_task import refresh_chapters_task

bp_admin = Blueprint('admin', __name__, url_prefix='/admin')


@bp_admin.before_request
def login():
    if not current_user.is_authenticated:
        abort(403)


@bp_admin.route('/mange', methods=['GET'])
def mange():
    return render_template('mange.html', chapter_count=Chapter.query.count(),
                           comic_count=Comic.query.count(),
                           comics=Comic.query.all(),
                           task_id=session.get('task_id'),
                           enable_celery=current_app.config['ENABLE_CELERY'],
                           running=session.get('task_id') is not None)


@bp_admin.route('/refresh_comics')
def refresh_comics():
    return jsonify(task.refresh_comics())


@bp_admin.route('/refresh_chapters')
def refresh_chapters():
    if current_app.config['ENABLE_CELERY']:
        if session.get('task_id') is None:
            t = refresh_chapters_task.apply_async()
            session['task_id'] = t.id
            return session['task_id']
        else:
            result = refresh_chapters_task.AsyncResult(session['task_id'])
            if result.state == 'SUCCESS' or result.state == 'FAILURE':
                t = refresh_chapters_task.apply_async()
                session['task_id'] = t.id
                return session['task_id']
            return 'Already running', 400
    return jsonify(task.refresh_chapters())


@bp_admin.route('/tasks/status/<task_id>')
def task_status(task_id):
    result = refresh_chapters_task.AsyncResult(task_id)
    if result.state == 'PENDING':
        response = {
            'state': result.state,
            'progress': 0,
        }
    elif result.state != 'FAILURE':
        response = {
            'state': result.state,
            'progress': result.info.get('progress', 0),
        }
        if result.state == 'SUCCESS':
            session.pop('task_id')
        if 'result' in result.info:
            response['result'] = result.info['result']
    else:
        # something went wrong in the background job
        session.pop('task_id')
        response = {
            'state': result.state,
            'progress': 0,
            'status': str(result.info),  # this is the exception raised
        }
    return jsonify(response)


@bp_admin.route('/refresh_comic_images')
def refresh_comic_images():
    return jsonify(task.refresh_comic_images())

ishuhui/controllers/auth.py
from flask import Blueprint, render_template, abort, current_app, flash, redirect, session, url_for
from flask import request
from flask_login import login_user, logout_user, current_user

from ..models.user import User

bp_auth = Blueprint('auth', __name__)


@bp_auth.before_request
def csrf_protect():
    if request.method == "POST":
        token = session.pop('_csrf_token', None)
        request_token = request.form.get('_csrf_token')
        if not token or token != request_token:
            abort(403)


@bp_auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET' and not current_user.is_authenticated:
        return render_template('login.html')
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if current_app.config['USERNAME'] != username or current_app.config['PASSWORD'] != password:
            flash('Login failed!', 'danger')
            return redirect(request.url)
        else:
            login_user(User())
            flash('Login succeed!', 'success')
            return redirect(url_for('admin.mange'))
    return redirect('/')


@bp_auth.route('/logout', methods=['GET'])
def logout():
    if not current_user.is_authenticated:
        abort(403)
    logout_user()
    return redirect('/')

ishuhui/controllers/comic.py
import re, requests
from flask import render_template, Blueprint, json, abort, redirect, request, jsonify, url_for, flash

import ishuhui.data as data
from ishuhui.extensions.flasksqlalchemy import db

bp_comic = Blueprint('comic', __name__)


@bp_comic.route('/')
def latest_chapters():
    chapters = data.get_latest_chapters(12)
    return render_template('latest.html', comic=None, chapters=chapters)


@bp_comic.route('/comics')
def comics():
    classify_id = request.args.get('classify_id')
    comics = data.get_comics(classify_id)
    return render_template('comics.html', comics=comics)


@bp_comic.route('/comics/<int:comic_id>/chapters')
def chapters(comic_id):
    comic = data.get_comic(comic_id)
    chapters = data.get_chapters(comic_id)
    return render_template('chapters.html', comic=comic, chapters=chapters)


image_pattern = re.compile(r'<img [^>]*src="([^"]+)')


def get_images_from_url(url):
    html = requests.get(url).text
    images = image_pattern.findall(html)
    return images


@bp_comic.route('/refresh_chapters/<int:chapter_id>', methods=['GET'])
def refresh_chapter(chapter_id):
    chapter = data.get_chapter(chapter_id)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(chapter_id) + '.html'
    images = get_images_from_url(url)
    chapter.images = json.dumps(images)
    db.session.commit()
    flash('Refresh succeed!', 'success')
    return redirect(url_for('comic.chapter', comic_id=chapter.comic().id, chapter_id=chapter.id))


@bp_comic.route('/comics/<int:comic_id>/chapters/<int:chapter_id>')
def chapter(comic_id, chapter_id):
    comic = data.get_comic(comic_id)
    chapter = data.get_chapter(chapter_id)
    next_chapter = data.get_next_chapter(comic_id, chapter.chapter_number)
    prev_chapter = data.get_prev_chapter(comic_id, chapter.chapter_number)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(
        chapter_id) + '.html'
    if chapter.comic_id != comic_id:
        abort(404)
    if chapter.images:
        images = json.loads(chapter.images)
    else:
        images = get_images_from_url(url)
        chapter.images = json.dumps(images)
        db.session.commit()
    return render_template(
        'images.html',
        comic=comic,
        chapter=chapter,
        next_chapter=next_chapter,
        prev_chapter=prev_chapter,
        images=images,
        url=url)

ishuhui/controllers/error.py
from flask import render_template, Blueprint

bp_error = Blueprint('error', __name__, template_folder="../templates/error")


@bp_error.app_errorhandler(403)
def page_not_found(error):
    return render_template('error.html', error=error), 403


@bp_error.app_errorhandler(404)
def page_not_found(error):
    return render_template('error.html', error=error), 404


@bp_error.app_errorhandler(500)
def server_error(error):
    return render_template('error.html', error=error), 500

ishuhui/templates/chapters.html
{% extends "base/layout.html" %}
{% block title %}{{ comic.title }}{% endblock %}
{% block content %}
    <div class="chapters-content card mdui-card mb-3">
        <img class="chapters-img" src="{{ comic.front_cover }}">
        {% with transparent = True %}
            {% include 'base/navbar.html' %}
        {% endwith %}
        <div class="card-body text-white bg-half-transparent">
            <h3 class="card-title">{{ comic.title }}</h3>
            <p class="card-text">{{ comic.description }}</p>
        </div>
    </div>
    <div id="chapters">
        <input type="search" class="search mb-3 form-control form-control-lg"
               placeholder="Search for title or chapter number from {{ chapters|length }} chapters.">
        <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
            {% for chapter in chapters %}
                <div class="col col-xs-6 col-sm-4 col-md-3 col-lg-2 mb-3">
                    <div class="card mdui-card mdui-hoverable">
                        <div class="card-body">
                            <h6 class="card-title title">{{ chapter.title }}</h6>
                            <footer>
                                <p class="card-text">
                                    <small class="text-muted chapter_number">第{{ chapter.chapter_number }}话</small>
                                </p>
                                <a href="{{ url_for('comic.chapter', comic_id=chapter.comic_id, chapter_id=chapter.id) }}"
                                   class="btn btn-sm btn-primary">View</a>
                            </footer>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ super() }}
    <script>
        var options = {
            valueNames: ['title', 'chapter_number'],
            listClass: 'row'
        };
        var list = new List('chapters', options);
        list.on('updated', function () {
            $('.row').masonry();
        })
    </script>
{% endblock %}

ishuhui/templates/comics.html
{% extends "base/layout.html" %}
{% set classify_id = request.args.get('classify_id') %}
{% block title %}
    {% if classify_id == '2' %}
        国产
    {% elif classify_id == '3' %}
        鼠绘
    {% elif classify_id == '4' %}
        热血
    {% elif classify_id == None %}
        所有
    {% endif %}
{% endblock %}
{% block content %}
    {% include 'base/navbar.html' %}
    <div class="mt-3">
        <div id="comics">
            <input type="search" class="search mb-3 form-control form-control-lg"
                   placeholder="Search from {{ comics|length }} comics.">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for comic in comics %}
                    <div class="col col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-3">
                        <div class="card mdui-card mdui-hoverable">
                            <img class="card-img-top" src="{{ comic.front_cover }}">
                            <div class="card-body">
                                <h4 class="title card-title">{{ comic.title }}</h4>
                                <p class="description card-text">{{ comic.description }}
                                    {% if comic.author %}
                                        <small class="text-muted"><em> -- {{ comic.author }}</em></small>
                                    {% endif %}
                                </p>
                                <footer>
                                    <p class="card-text">
                                        <small class="refresh_time text-muted">{{ comic.refresh_time }}</small>
                                    </p>
                                    <a href="{{ url_for('comic.chapters', comic_id=comic.id) }}"
                                       class="btn btn-primary btn-sm">View</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %} {% block footer %} {{ super() }}
    <script>
        var options = {
            valueNames: ['title', 'description'],
            listClass: 'row'
        };
        var list = new List('comics', options);
        list.on('updated', function () {
            $('.row').masonry();
        });

        $('.row').imagesLoaded().progress(function () {
            $('.row').masonry();
        });
    </script>
{% endblock %}

ishuhui/templates/error.html
{% extends "base/layout.html" %} {% block content %}
    <div class="mt-3">
        <div class="alert alert-danger" role="alert">
            <p>
                <strong>ERROR: </strong>{{ error }}.
            </p>
            <hr>
            <p class="mb-0">Go <a class="alert-link" href="/">Home.</a></p>
        </div>
    </div>
{% endblock %}

ishuhui/templates/images.html
{% extends "base/layout.html" %}
{% block head %}
    {{ super() }}
    <link href="https://cdn.bootcss.com/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet">
{% endblock %}
{% block title %}{{ comic.title }}{{ chapter.chapter_number }}-{{ chapter.title }}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="mt-3 col-md-10">
            <ol class="breadcrumb" id="top">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('comic.chapters', comic_id=comic.id) }}">{{ comic.title }}</a>
                </li>
                <li class="breadcrumb-item active">第{{ chapter.chapter_number }}话--<strong>{{ chapter.title }}</strong></li>
            </ol>
            {% include 'base/msg.html' %}
            <div class="card mdui-card" id="images">
                <div class="card-header">
                    {% if prev_chapter %}
                        <a class="float-left"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=prev_chapter.id) }}">Prev({{ prev_chapter.title }})</a>
                    {% endif %}
                    {% if next_chapter %}
                        <a class="float-right"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=next_chapter.id) }}">Next({{ next_chapter.title }})</a>
                    {% endif %}
                </div>
                <div>
                    {% for image in images %}
                        <a class="image" href="{{ image }}">
                            <img src="{{ image }}" class="img-fluid mb-1" style="width:100%;display:block;">
                        </a>
                    {% endfor %}
                </div>
                <div class="card-footer">
                    {% if prev_chapter %}
                        <a class="float-left"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=prev_chapter.id) }}">Prev({{ prev_chapter.title }})</a>
                    {% endif %}
                    {% if next_chapter %}
                        <a class="float-right"
                           href="{{ url_for('comic.chapter', comic_id=comic.id, chapter_id=next_chapter.id) }}">Next({{ next_chapter.title }})</a>
                    {% endif %}
                </div>
            </div>
            <a href="#top" class="mdui-fab mdui-fab-fixed mdui-ripple" style="bottom: 100px"><i class="mdui-icon material-icons">&#xe5d8;</i></a>
            <a href="{{ url_for('comic.refresh_chapter', chapter_id=chapter.id) }}" class="mdui-color-green-400 mdui-text-color-white mdui-fab mdui-fab-fixed mdui-ripple"><i class="mdui-icon material-icons">&#xe5d5;</i></a>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.image').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true,
                    navigateByImgClick: true,
                    tCounter: '<span class="mfp-counter">%curr% of %total% Pictures</span>',
                    preload: [0, 1] // Will preload 0 - before current, and 1 after the current image
                }
            });
        });
    </script>
{% endblock %}

ishuhui/templates/index.html
{% extends "layout.html" %} {% block content %}
    <div class="mt-3">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
            Welcome! Visit on <a href="https://github.com/lufficc/flask_ishuhui" target="_blank" class="alert-link">GitHub</a>.
        </div>

        <div id="comics">
            <input type="search" class="search mb-3 form-control form-control-lg"
                       placeholder="Search from {{ comics|length }} comics.">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for comic in comics %}
                    <div class="col col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 mb-3">
                        <div class="card mdui-card mdui-hoverable">
                            <img class="card-img-top" src="{{ comic.front_cover }}">
                            <div class="card-body">
                                <h4 class="title card-title">{{ comic.title }}</h4>
                                <p class="description card-text">{{ comic.description }}
                                    {% if comic.author %}
                                        <small class="text-muted"><em> -- {{ comic.author }}</em></small>
                                    {% endif %}
                                </p>
                                <footer>
                                    <p class="card-text">
                                        <small class="refresh_time text-muted">{{ comic.refresh_time }}</small>
                                    </p>
                                    <a href="{{ url_for('comic.chapters', comic_id=comic.id) }}"
                                       class="btn btn-primary btn-sm">View</a>
                                </footer>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %} {% block footer %} {{ super() }}
    <script>
        var options = {
            valueNames: ['title', 'description'],
            listClass: 'row'
        };
        var list = new List('comics', options);
        list.on('updated', function () {
            $('.row').masonry();
        });

        $('.row').imagesLoaded().progress(function () {
            $('.row').masonry();
        });
    </script>
{% endblock %}

ishuhui/templates/latest.html
{% extends "base/layout.html" %}
{% block title %}最新{% endblock %}
{% block content %}
    {% include 'base/navbar.html' %}
    <div class="mt-3">
        <div id="chapters">
            <div class="row" data-masonry='{ "itemSelector": ".col", "columnWidth":".col" }'>
                {% for chapter in chapters %}
                    {% set comic = chapter.comic() %}
                    <div class="col col-sm-6 col-md-4 mb-3">
                        <div class="card mdui-card mdui-card-hoverable text-white"
                             style="background: url('{{ chapter.front_cover }}') no-repeat center;background-size: cover">
                            <div class="card-body" style="background-color: rgba(33,33,33,0.6)">
                                <h3 class="card-title comic-title">{{ comic.title }}{{ chapter.chapter_number }}话</h3>
                                <h5 class="card-title chapter-title">{{ chapter.title }}</h5>
                                <p class="card-text comic-description">{{ comic.description }}</p>
                                <p class="card-text">
                                    <small>{{ chapter.refresh_time }}</small>
                                </p>
                                <a href="{{ url_for('comic.chapter', comic_id=chapter.comic_id, chapter_id=chapter.id) }}"
                                   class="btn btn-primary">View</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

ishuhui/templates/login.html
{% extends "base/layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="row justify-content-center mt-5 mb-5">
        <div class="col-md-6">
            {% include 'base/msg.html' %}
            <div class="card mdui-card">
                <div class="card-body">
                    <h4 class="card-title">Login</h4>
                    <form method="post" action="{{ url_for('auth.login') }}">
                        <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" class="form-control" id="username" placeholder="Enter username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                        </div>
                        <button type="submit" class="btn btn-success">Login</button>
                        <a class="btn btn-link" href="/">Go home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ishuhui/templates/mange.html
{% extends "base/layout.html" %}
{% block title %}Mange{% endblock %}
{% block content %}
    {% include 'base/navbar.html' %}
    {% include 'base/msg.html' %}
    <div class="card-deck mt-3">
        <div class="card text-center mdui-card mb-3">
            <div class="card-body">
                <h3 class="card-title">{{ comic_count }} <span class="text-muted">Comics</span></h3>
            </div>
        </div>
        <div class="card text-center mdui-card mb-3">
            <div class="card-body">
                <h3 class="card-title">{{ chapter_count }} <span class="text-muted">Chapters</span></h3>
            </div>
        </div>
    </div>
    <div class="card-deck mt-3">
        <div class="card text-center mdui-card mb-3">
            <div class="card-body">
                <h4 class="card-title">Refresh Comics</h4>
                <p class="card-text">Refresh all comics to keep update.</p>
                <button class="btn btn-primary" onclick="request('{{ url_for("admin.refresh_comics") }}', $(this), 'comics')">Refresh</button>
            </div>
        </div>
        <div class="card text-center mdui-card mb-3">
            {% if enable_celery %}
                <div class="progress d-none" id="progress-bar-wrapper" style="height: 3px;">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" id="progress-bar" role="progressbar" style="width: 0;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">Refresh Chapters</h4>
                <p class="card-text">Refresh all chapters to keep update.<span id="state" class="badge badge-secondary"></span></p>
                {% if enable_celery %}
                    <button class="btn btn-primary" id="btn_refresh_chapters" onclick="refreshChapters('{{ url_for("admin.refresh_chapters") }}', $(this))">Refresh</button>
                {% else %}
                    <button class="btn btn-primary" onclick="request('{{ url_for("admin.refresh_chapters") }}', $(this), 'chapters')">Refresh</button>
                {% endif %}
            </div>
        </div>
    </div>
    <ul class="list-group">
        {% for comic in comics %}
            <a class="list-group-item list-group-item-action" href="{{ url_for('comic.chapters', comic_id=comic.id) }}">
                <img src="{{ comic.front_cover }}" height="20" class="pr-2">
                {{ comic.title }}
                <span class="badge badge-secondary badge-pill float-right">{{ comic.chapters_count }}</span>
            </a>
        {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
    {{ super() }}
    <script>
        {% if enable_celery and running %}
            setToRunningState($('#btn_refresh_chapters'), "{{ task_id }}");
        {% endif %}
        function setToRunningState(loader, task_id) {
            var progressBar = $('#progress-bar-wrapper');
            loader.text('Refreshing...').addClass('disabled').prop('disabled', true);
            progressBar.removeClass('d-none');
            update_progress("/admin/tasks/status/" + task_id, loader)
        }

        function refreshChapters(url, loader) {
            var progressBar = $('#progress-bar-wrapper');
            loader.text('Refreshing...').addClass('disabled').prop('disabled', true);
            progressBar.removeClass('d-none');
            $.get(url, function (res) {
                //res : task_id
                update_progress("/admin/tasks/status/" + res, loader)
            }).fail(function () {
                messge('Refresh failed', 'error');
                loader.text('Refresh').removeClass('disabled').prop('disabled', false);
            });
        }

        function setProgress(progress) {
            var progressBar = $('#progress-bar');
            progressBar.css('width', parseInt(100 * progress) + '%');
            progressBar.attr('aria-valuenow', parseInt(100 * progress));
        }

        function update_progress(url, loader) {
            $.get(url, function (res) {
                var progress = res['progress'];
                var state = res['state'];
                $('#state').text(state);
                setProgress(progress);
                if (state !== 'PENDING' && state !== 'PROGRESS') {
                    if (state === 'SUCCESS') {
                        messge('Refresh succeed.');
                    } else {
                        messge('Refresh failed, ' + res['status']);
                    }
                    setProgress(0);
                    $('#progress-bar-wrapper').addClass('d-none');
                    loader.text('Refresh').removeClass('disabled').prop('disabled', false);
                }
                else {
                    // rerun every second
                    setTimeout(function () {
                        update_progress(url, loader);
                    }, 5000);
                }
            }).fail(function () {
                setTimeout(function () {
                    update_progress(url, loader);
                }, 1000);
            });
        }

        function request(url, loader, resource) {
            loader.text('Refreshing...').addClass('disabled').prop('disabled', true);
            $.get(url, function (res) {
                messge('Refresh succeed, refreshed ' + res.length + ' ' + resource);
            }).fail(function () {
                messge('Refresh failed', 'error');
            }).always(function () {
                loader.text('Refresh').removeClass('disabled').prop('disabled', false);
            });
        }
    </script>
{% endblock %}

ishuhui/templates/navbar.html
{% set classify_id = request.args.get('classify_id') %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
        <img src="https://i.loli.net/2017/08/26/59a15ddf9c36f.png" width="30" height="30" class="d-inline-block align-top" alt="">
        鼠绘漫画
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item{% if request.path=="/" %} active{% endif %}">
                <a class="nav-link" href="/">Latest <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item{% if not classify_id and request.path=="/comics" %} active{% endif %}">
                <a class="nav-link" href="{{ url_for('comic.comics') }}">All Comics</a>
            </li>
            <li class="nav-item dropdown{% if classify_id %} active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                {% set comics_url = url_for('comic.comics') %}
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item{% if classify_id == '2' %} active{% endif %}" href="{{ comics_url+'?classify_id=2' }}">国产</a>
                    <a class="dropdown-item{% if classify_id == '3' %} active{% endif %}" href="{{ comics_url+'?classify_id=3' }}">鼠绘</a>
                    <a class="dropdown-item{% if classify_id == '4' %} active{% endif %}" href="{{ comics_url+'?classify_id=4' }}">热血</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://lufficc.com/">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/lufficc/flask_ishuhui.git">GitHub</a>
            </li>
        </ul>
    </div>
</nav>