ishuhui/controllers/auth.py
from flask import Blueprint, render_template, abort, current_app, flash, redirect, session, url_for
from flask import request
from flask_login import login_user, logout_user, current_user

from ..models.user import User

bp_auth = Blueprint('auth', __name__)


@bp_auth.before_request
def csrf_protect():
    if request.method == "POST":
        token = session.pop('_csrf_token', None)
        request_token = request.form.get('_csrf_token')
        if not token or token != request_token:
            abort(403)


@bp_auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET' and not current_user.is_authenticated:
        return render_template('login.html')
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if current_app.config['USERNAME'] != username or current_app.config['PASSWORD'] != password:
            flash('Login failed!', 'danger')
            return redirect(request.url)
        else:
            login_user(User())
            flash('Login succeed!', 'success')
            return redirect(url_for('admin.mange'))
    return redirect('/')


@bp_auth.route('/logout', methods=['GET'])
def logout():
    if not current_user.is_authenticated:
        abort(403)
    logout_user()
    return redirect('/')

ishuhui/controllers/comic.py
import re, requests
from flask import render_template, Blueprint, json, abort, redirect, request, jsonify, url_for, flash

import ishuhui.data as data
from ishuhui.extensions.flasksqlalchemy import db

bp_comic = Blueprint('comic', __name__)


@bp_comic.route('/')
def latest_chapters():
    chapters = data.get_latest_chapters(12)
    return render_template('latest.html', comic=None, chapters=chapters)


@bp_comic.route('/comics')
def comics():
    classify_id = request.args.get('classify_id')
    comics = data.get_comics(classify_id)
    return render_template('comics.html', comics=comics)


@bp_comic.route('/comics/<int:comic_id>/chapters')
def chapters(comic_id):
    comic = data.get_comic(comic_id)
    chapters = data.get_chapters(comic_id)
    return render_template('chapters.html', comic=comic, chapters=chapters)


image_pattern = re.compile(r'<img [^>]*src="([^"]+)')


def get_images_from_url(url):
    html = requests.get(url).text
    images = image_pattern.findall(html)
    return images


@bp_comic.route('/refresh_chapters/<int:chapter_id>', methods=['GET'])
def refresh_chapter(chapter_id):
    chapter = data.get_chapter(chapter_id)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(chapter_id) + '.html'
    images = get_images_from_url(url)
    chapter.images = json.dumps(images)
    db.session.commit()
    flash('Refresh succeed!', 'success')
    return redirect(url_for('comic.chapter', comic_id=chapter.comic().id, chapter_id=chapter.id))


@bp_comic.route('/comics/<int:comic_id>/chapters/<int:chapter_id>')
def chapter(comic_id, chapter_id):
    comic = data.get_comic(comic_id)
    chapter = data.get_chapter(chapter_id)
    next_chapter = data.get_next_chapter(comic_id, chapter.chapter_number)
    prev_chapter = data.get_prev_chapter(comic_id, chapter.chapter_number)
    url = 'http://www.ishuhui.net/ComicBooks/ReadComicBooksToIsoV1/' + str(
        chapter_id) + '.html'
    if chapter.comic_id != comic_id:
        abort(404)
    if chapter.images:
        images = json.loads(chapter.images)
    else:
        images = get_images_from_url(url)
        chapter.images = json.dumps(images)
        db.session.commit()
    return render_template(
        'images.html',
        comic=comic,
        chapter=chapter,
        next_chapter=next_chapter,
        prev_chapter=prev_chapter,
        images=images,
        url=url)

ishuhui/templates/base/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="referrer" content="no-referrer">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} 漫画</title>
        <link href="//cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/mdui/0.3.0/css/mdui.min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='style.css') }}" rel=stylesheet>
        <link rel="shortcut icon" href="https://static.lufficc.com/favicon.ico"/>
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-81713716-4"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }

            gtag('js', new Date());
            gtag('config', 'UA-81713716-4');
        </script>
    {% endblock %}
</head>

<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
{% block footer %}
    <center class="mt-2 mb-2">&copy; Copyright 2017 By <a href="https://lufficc.com">lufficc</a>.</center>
    <div id="snackbar"></div>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/mdui/0.3.0/js/mdui.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="//cdn.bootcss.com/masonry/4.2.0/masonry.pkgd.min.js"></script>
    <script src="//cdn.bootcss.com/list.js/1.5.0/list.min.js"></script>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
{% endblock %}
</body>
</html>

ishuhui/templates/base/msg.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% set (category, message) = messages|first %}
        {% set category = 'info' if category == 'message' else category %}
        <div class="alert alert-{{ category }} alert-dismissible fade show mt-3" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}
{% endwith %}

ishuhui/templates/base/navbar.html
{% set classify_id = request.args.get('classify_id') %}
<nav class="font-weight-bold navbar navbar-expand-lg {% if transparent is defined %}navbar-dark bg-half-transparent{% else %}bg-light navbar-light{% endif %}">
    <a class="navbar-brand" href="/">
        <img src="https://i.loli.net/2017/08/26/59a15ddf9c36f.png" width="30" height="30" class="d-inline-block align-top" alt="">
        鼠绘漫画
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item{% if request.path=="/" %} active{% endif %}">
                <a class="nav-link" href="/">Latest <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item{% if not classify_id and request.path=="/comics" %} active{% endif %}">
                <a class="nav-link" href="{{ url_for('comic.comics') }}">All Comics</a>
            </li>
            <li class="nav-item dropdown{% if classify_id %} active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                {% set comics_url = url_for('comic.comics') %}
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item{% if classify_id == '2' %} active{% endif %}" href="{{ comics_url+'?classify_id=2' }}">国产</a>
                    <a class="dropdown-item{% if classify_id == '3' %} active{% endif %}" href="{{ comics_url+'?classify_id=3' }}">鼠绘</a>
                    <a class="dropdown-item{% if classify_id == '4' %} active{% endif %}" href="{{ comics_url+'?classify_id=4' }}">热血</a>
                </div>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ current_user.name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
                        <a class="dropdown-item{% if request.path==url_for('admin.mange') %} active{% endif %}" href="{{ url_for('admin.mange') }}">Mange</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav ml-auto justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="https://lufficc.com/">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/lufficc/flask_ishuhui.git">GitHub</a>
            </li>
        </ul>
    </div>
</nav>